version: "3.8"
services:
  sermon-processor:
    image: sermon-processor:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/usr/src/app/data
      - ./tmp:/usr/src/app/tmp
    env_file:
      - .env
    stdin_open: true
    tty: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./data:/usr/src/app/data
      - ./tmp:/usr/src/app/tmp
    command: pytest tests/
